# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('hsp-core', ['core'])
    module.source = [
        'model/hsp-simulator-impl.cc',
        'model/lookfree-skiplist-scheduler.cc',
        'model/skiplist.cc',
        ]

    #module_test = bld.create_ns3_module_test_library('hsp-core')
    #module_test.source = [
    #    'test/hsp-core-test-suite.cc',
    #    ]

    headers = bld(features='ns3header')
    headers.module = 'hsp-core'
    headers.source = [
        'model/hsp-simulator-impl.h',
        'model/lockfree-skiplist-scheduler.h',

        'model/ThreadPool.h',
        'model/skiplist.h',
        'model/sl_map.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

